version: 2
updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "17:00"
      timezone: "Europe/Ljubljana"

  # Laguna workspace
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "17:00"
      timezone: "Europe/Ljubljana"
