version: 2
updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "17:00"
      timezone: "Europe/Ljubljana"
    labels:
      - "A-CI/CD"
      - "T-Dep"
      - "D-1"

  # Laguna workspace
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: "cargo"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "17:00"
      timezone: "Europe/Ljubljana"
    labels:
      - "A-CI/CD"
      - "T-Dep"
      - "D-1"
