[package]
name = "laguna-backend"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
actix-web = "4"
sqlx = { version = "0.6.3", features = [
    "runtime-actix-rustls",
    "postgres",
    "uuid",
    "migrate",
    "macros",
    "time",
    "json",
] }
env_logger = "0.10.0"
log = "0.4.19"
actix-jwt-auth-middleware = "0.3.0"
jwt-compact = "0.7.0"
sha2 = "0.10"
chrono = { version = "*", features = ["serde"]}
uuid = { version = "*", features = ["serde", "v4", "fast-rng"] }
digest = { version = "0.10.7", default-features = false }
laguna = { package = "laguna-backend-internal", path = "crates/laguna-backend-internal" }
actix-web-httpauth = "0.8.0"

[dev-dependencies]
cargo-watch = "8.4.0"

# CLI for sqlx.
# More: https://github.com/launchbadge/sqlx/blob/main/sqlx-cli/README.md
sqlx-cli = { version = "0.6.3", default-features = false, features = [
    "rustls",
    "postgres",
] }
