[actix]
hosts = [
    ["127.0.0.1", 6969],
    ["localhost", 6969]
]
mode = "development"
enable-compression = true
enable-log = true
num-workers = "default"
backlog = "default"
max-connections = "default"
max-connection-rate = "default"
keep-alive = "default"
client-timeout = "default"
client-shutdown = "default"
shutdown-timeout = "default"

[actix.tls]
enabled = false
certificate = ""
private-key = ""

[application]

[application.auth]
secret-key = "some random shit"
password-pepper = "some random pepper shit"
access-token-lifetime-seconds = 86400 # 60 * 60 * 24 = 1 day
refresh-token-lifetime-seconds = 259200 # 60 * 60 * 24 * 3 = 3 days

[application.database]
proto = "postgres"
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "postgres"
name = "laguna_dev_db"

[application.frontend]
host = "127.0.0.1"
port = 4200

[application.tracker]
announce-url = "http://127.0.0.1:6969/peer/announce"
announce-interval = 1800

[application.mailer]
api-base-url = "http://api.postmarkapp.com/"
api-token = "some token"
sender-email = "bot@laguna.si"