CREATE TABLE IF NOT EXISTS "Block"
(
    id      UUID PRIMARY KEY         NOT NULL DEFAULT uuid_generate_v4(),
    at      TIMESTAMP WITH TIME ZONE NOT NULL,
    blocker INTEGER,
    blocked INTEGER,
    FOREIGN KEY (blocker) REFERENCES "User" (id) ON DELETE CASCADE NULL ON UPDATE CASCADE,
    FOREIGN KEY (blocked) REFERENCES "User" (id) ON DELETE CASCADE NULL ON UPDATE CASCADE
);