[package]
name = "laguna-backend-model"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { workspace = true }
actix-web = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
sha2 = { workspace = true }
digest = { workspace = true }