#![doc(html_logo_url = "https://sloveniaengineering.github.io/laguna-backend/logo.png")]
#![doc(html_favicon_url = "https://sloveniaengineering.github.io/laguna-backend/favicon.ico")]
#![doc(issue_tracker_base_url = "https://github.com/SloveniaEngineering/laguna-backend")]
pub mod already_exists;
pub mod login;
pub mod meta;
pub mod peer;
pub mod register;
pub mod torrent;
pub mod user;
pub mod validators;
