name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Actions
      uses: actions/checkout@v3
      
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag laguna-backend
        docker tag laguna-backend ghcr.io/sloveniaengineering/laguna-backend:${{github.sha}}
        docker tag laguna-backend ghcr.io/sloveniaengineering/laguna-backend:latest
        docker push --all-tags ghcr.io/sloveniaengineering/laguna-backend
