name: Docs

on:
  workflow_run:
    workflows:
      - Rust
    types:
      - completed

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
            path: |
                ~/.cargo/bin/
                ~/.cargo/registry/index/
                ~/.cargo/registry/cache/
                ~/.cargo/git/db/
                target/
            key: ubuntu-latest-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build Docs
        run: cargo doc --no-deps --document-private-items --workspace
      - name: Doc Index Page Redirection
        run: echo '<meta http-equiv="refresh" content="1; url=index.html">' > target/doc/index.html
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          user_name: "github-actions-laguna[bot]"
          user_email: "github-actions-laguna[bot]@users.noreply.github.com"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: documentation
          publish_dir: target/doc
          force_orphan: true
