//! Middleware logic.
#![doc(html_logo_url = "https://sloveniaengineering.github.io/laguna-backend/logo.png")]
#![doc(html_favicon_url = "https://sloveniaengineering.github.io/laguna-backend/favicon.ico")]
#![doc(issue_tracker_base_url = "https://github.com/SloveniaEngineering/laguna-backend")]
pub mod auth;
pub mod auth_helper;
pub mod consts;
pub mod exclusive;
pub mod mime;
